project_id = "bllfldhfrtsobqssuupu"

[functions.generate-master]
verify_jwt = false

[functions.generate-formats]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false